version: "3"

services:
  flask:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - 8001:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - flask
