version: "3"

services:
  flask:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
      - ROOT_URL=https://cowboyz.shirleyyin.com
      - DEBUG=False
    restart: always
    networks:
      - default

  nginx:
    image: nginx:stable
    ports:
      - 8001:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - flask
    networks:
      - default
      - haproxy_default

networks:
  default:
    driver: bridge
  haproxy_default:
    external: true

