version: "3"

services:
  flask:
    # container_name: cowboyz
    build:
      context: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - VIRTUAL_HOST=cowboyz.shirleyyin.com

networks:
  default:
    external:
      name: nginxproxy_default
