version: "3"

services:
  flask:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    restart: always
    networks:
      - default

  nginx:
    image: nginx:stable
    expose:
      - "80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - flask
    networks:
      - default
      - nginx-proxy_nginx-proxy
    restart: always
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=cowboyz.shirleyyin.com
      - LETSENCRYPT_HOST=cowboyz.shirleyyin.com
      - LETSENCRYPT_EMAIL=contact@shirleyyin.com

networks:
  default:
    driver: bridge
  nginx-proxy_nginx-proxy:
    external: true
